name: Check TypeScript

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - client/**
      - server/**
      - shared/**
      - worker/**

jobs:
  check-typescript:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        application:
          - client
          - server
          - shared
          - worker

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - name: Setup Project
        working-directory: ${{ matrix.application }}
        run: pnpm install

      - name: Generate Routes
        working-directory: ${{ matrix.application }}
        if: ${{ matrix.application == 'client' }}
        run: pnpm tsr generate

      - name: Check TypeScript
        working-directory: ${{ matrix.application }}
        run: pnpm lint
